# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

name: sophia-deb12mdl
services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    #image: docker.io/bitnami/moodle:4.4
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
  jobe:
    image: trampgeek/jobeinabox:latest
    restart: always
    ports:
      - '4000:80'
      # Moode HTTP security Config
      # cURL allowed ports list, curlsecurityallowedport: 4000
      # cURL blocked hosts list curlsecurityblockedhosts: empty
      # Jobe server qtype_coderunner | jobe_host: host.docker.internal:4000
#  vpl:
#    image: jcrodriguezvpl/jail-alpine-full:latest
#   restart: always
#    ports:
#      - '5000:80'
#      # Lista de servidores de execução mod_vpl | jail_servers: host.docker.internal:5000
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
